/*
Apify API

Testing WebhooksWebhooksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_WebhooksWebhooksAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WebhooksWebhooksAPIService WebhookDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookId string

		resp, httpRes, err := apiClient.WebhooksWebhooksAPI.WebhookDelete(context.Background(), webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksWebhooksAPIService WebhookGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookId string

		resp, httpRes, err := apiClient.WebhooksWebhooksAPI.WebhookGet(context.Background(), webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksWebhooksAPIService WebhookPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookId string

		resp, httpRes, err := apiClient.WebhooksWebhooksAPI.WebhookPut(context.Background(), webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksWebhooksAPIService WebhookTestPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookId string

		resp, httpRes, err := apiClient.WebhooksWebhooksAPI.WebhookTestPost(context.Background(), webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksWebhooksAPIService WebhookWebhookDispatchesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookId string

		resp, httpRes, err := apiClient.WebhooksWebhooksAPI.WebhookWebhookDispatchesGet(context.Background(), webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksWebhooksAPIService WebhooksGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WebhooksWebhooksAPI.WebhooksGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksWebhooksAPIService WebhooksPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WebhooksWebhooksAPI.WebhooksPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
