/*
Apify API

Testing LastActorTaskRunsDefaultRequestQueueAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_LastActorTaskRunsDefaultRequestQueueAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueDelete(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueGet(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueHeadGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueHeadGet(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueHeadLockPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueHeadLockPost(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueuePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueuePut(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueRequestDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string
		var requestId string

		httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueRequestDelete(context.Background(), actorTaskId, requestId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueRequestGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string
		var requestId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueRequestGet(context.Background(), actorTaskId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueRequestLockDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string
		var requestId string

		httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueRequestLockDelete(context.Background(), actorTaskId, requestId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueRequestLockPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string
		var requestId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueRequestLockPut(context.Background(), actorTaskId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueRequestPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string
		var requestId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueRequestPut(context.Background(), actorTaskId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueRequestsBatchDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueRequestsBatchDelete(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueRequestsBatchPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueRequestsBatchPost(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueRequestsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueRequestsGet(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueRequestsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueRequestsPost(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultRequestQueueAPIService ActorTaskRunsLastRequestQueueRequestsUnlockPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultRequestQueueAPI.ActorTaskRunsLastRequestQueueRequestsUnlockPost(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
