/*
Apify API

Testing StorageRequestQueuesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_StorageRequestQueuesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StorageRequestQueuesAPIService RequestQueueDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string

		httpRes, err := apiClient.StorageRequestQueuesAPI.RequestQueueDelete(context.Background(), queueId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesAPIService RequestQueueGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string

		resp, httpRes, err := apiClient.StorageRequestQueuesAPI.RequestQueueGet(context.Background(), queueId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesAPIService RequestQueuePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string

		resp, httpRes, err := apiClient.StorageRequestQueuesAPI.RequestQueuePut(context.Background(), queueId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesAPIService RequestQueueRequestsBatchDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string

		resp, httpRes, err := apiClient.StorageRequestQueuesAPI.RequestQueueRequestsBatchDelete(context.Background(), queueId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesAPIService RequestQueueRequestsBatchPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string

		resp, httpRes, err := apiClient.StorageRequestQueuesAPI.RequestQueueRequestsBatchPost(context.Background(), queueId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesAPIService RequestQueuesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.StorageRequestQueuesAPI.RequestQueuesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesAPIService RequestQueuesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.StorageRequestQueuesAPI.RequestQueuesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
