/*
Apify API

Testing DefaultKeyValueStoreAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_DefaultKeyValueStoreAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultKeyValueStoreAPIService ActorRunKeyValueStoreDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		httpRes, err := apiClient.DefaultKeyValueStoreAPI.ActorRunKeyValueStoreDelete(context.Background(), runId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultKeyValueStoreAPIService ActorRunKeyValueStoreGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.DefaultKeyValueStoreAPI.ActorRunKeyValueStoreGet(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultKeyValueStoreAPIService ActorRunKeyValueStoreKeysGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.DefaultKeyValueStoreAPI.ActorRunKeyValueStoreKeysGet(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultKeyValueStoreAPIService ActorRunKeyValueStorePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.DefaultKeyValueStoreAPI.ActorRunKeyValueStorePut(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultKeyValueStoreAPIService ActorRunKeyValueStoreRecordDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string
		var recordKey string

		httpRes, err := apiClient.DefaultKeyValueStoreAPI.ActorRunKeyValueStoreRecordDelete(context.Background(), runId, recordKey).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultKeyValueStoreAPIService ActorRunKeyValueStoreRecordGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string
		var recordKey string

		resp, httpRes, err := apiClient.DefaultKeyValueStoreAPI.ActorRunKeyValueStoreRecordGet(context.Background(), runId, recordKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultKeyValueStoreAPIService ActorRunKeyValueStoreRecordPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string
		var recordKey string

		resp, httpRes, err := apiClient.DefaultKeyValueStoreAPI.ActorRunKeyValueStoreRecordPost(context.Background(), runId, recordKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultKeyValueStoreAPIService ActorRunKeyValueStoreRecordPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string
		var recordKey string

		resp, httpRes, err := apiClient.DefaultKeyValueStoreAPI.ActorRunKeyValueStoreRecordPut(context.Background(), runId, recordKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultKeyValueStoreAPIService ActorRunKeyValueStoreRecordsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.DefaultKeyValueStoreAPI.ActorRunKeyValueStoreRecordsGet(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
