/*
Apify API

Testing ActorBuildsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_ActorBuildsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ActorBuildsAPIService ActorBuildAbortPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var buildId string

		resp, httpRes, err := apiClient.ActorBuildsAPI.ActorBuildAbortPost(context.Background(), buildId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorBuildsAPIService ActorBuildDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var buildId string

		httpRes, err := apiClient.ActorBuildsAPI.ActorBuildDelete(context.Background(), buildId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorBuildsAPIService ActorBuildGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var buildId string

		resp, httpRes, err := apiClient.ActorBuildsAPI.ActorBuildGet(context.Background(), buildId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorBuildsAPIService ActorBuildLogGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var buildId string

		resp, httpRes, err := apiClient.ActorBuildsAPI.ActorBuildLogGet(context.Background(), buildId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorBuildsAPIService ActorBuildOpenapiJsonGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var buildId string

		resp, httpRes, err := apiClient.ActorBuildsAPI.ActorBuildOpenapiJsonGet(context.Background(), buildId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorBuildsAPIService ActorBuildsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ActorBuildsAPI.ActorBuildsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
