/*
Apify API

Testing StorageKeyValueStoresAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_StorageKeyValueStoresAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StorageKeyValueStoresAPIService KeyValueStoreDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storeId string

		httpRes, err := apiClient.StorageKeyValueStoresAPI.KeyValueStoreDelete(context.Background(), storeId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageKeyValueStoresAPIService KeyValueStoreGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storeId string

		resp, httpRes, err := apiClient.StorageKeyValueStoresAPI.KeyValueStoreGet(context.Background(), storeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageKeyValueStoresAPIService KeyValueStoreKeysGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storeId string

		resp, httpRes, err := apiClient.StorageKeyValueStoresAPI.KeyValueStoreKeysGet(context.Background(), storeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageKeyValueStoresAPIService KeyValueStorePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storeId string

		resp, httpRes, err := apiClient.StorageKeyValueStoresAPI.KeyValueStorePut(context.Background(), storeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageKeyValueStoresAPIService KeyValueStoreRecordDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storeId string
		var recordKey string

		httpRes, err := apiClient.StorageKeyValueStoresAPI.KeyValueStoreRecordDelete(context.Background(), storeId, recordKey).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageKeyValueStoresAPIService KeyValueStoreRecordGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storeId string
		var recordKey string

		resp, httpRes, err := apiClient.StorageKeyValueStoresAPI.KeyValueStoreRecordGet(context.Background(), storeId, recordKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageKeyValueStoresAPIService KeyValueStoreRecordHead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storeId string
		var recordKey string

		httpRes, err := apiClient.StorageKeyValueStoresAPI.KeyValueStoreRecordHead(context.Background(), storeId, recordKey).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageKeyValueStoresAPIService KeyValueStoreRecordPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storeId string
		var recordKey string

		resp, httpRes, err := apiClient.StorageKeyValueStoresAPI.KeyValueStoreRecordPost(context.Background(), storeId, recordKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageKeyValueStoresAPIService KeyValueStoreRecordPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storeId string
		var recordKey string

		resp, httpRes, err := apiClient.StorageKeyValueStoresAPI.KeyValueStoreRecordPut(context.Background(), storeId, recordKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageKeyValueStoresAPIService KeyValueStoreRecordsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storeId string

		resp, httpRes, err := apiClient.StorageKeyValueStoresAPI.KeyValueStoreRecordsGet(context.Background(), storeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageKeyValueStoresAPIService KeyValueStoresGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.StorageKeyValueStoresAPI.KeyValueStoresGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageKeyValueStoresAPIService KeyValueStoresPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.StorageKeyValueStoresAPI.KeyValueStoresPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
