/*
Apify API

Testing SchedulesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_SchedulesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SchedulesAPIService ScheduleDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var scheduleId string

		resp, httpRes, err := apiClient.SchedulesAPI.ScheduleDelete(context.Background(), scheduleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchedulesAPIService ScheduleGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var scheduleId string

		resp, httpRes, err := apiClient.SchedulesAPI.ScheduleGet(context.Background(), scheduleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchedulesAPIService ScheduleLogGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var scheduleId string

		resp, httpRes, err := apiClient.SchedulesAPI.ScheduleLogGet(context.Background(), scheduleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchedulesAPIService SchedulePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var scheduleId string

		resp, httpRes, err := apiClient.SchedulesAPI.SchedulePut(context.Background(), scheduleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchedulesAPIService SchedulesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SchedulesAPI.SchedulesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchedulesAPIService SchedulesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SchedulesAPI.SchedulesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
