/*
Apify API

Testing LastActorRunsDefaultKeyValueStoreAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_LastActorRunsDefaultKeyValueStoreAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LastActorRunsDefaultKeyValueStoreAPIService ActRunsLastKeyValueStoreDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		httpRes, err := apiClient.LastActorRunsDefaultKeyValueStoreAPI.ActRunsLastKeyValueStoreDelete(context.Background(), actorId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultKeyValueStoreAPIService ActRunsLastKeyValueStoreGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultKeyValueStoreAPI.ActRunsLastKeyValueStoreGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultKeyValueStoreAPIService ActRunsLastKeyValueStoreKeysGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultKeyValueStoreAPI.ActRunsLastKeyValueStoreKeysGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultKeyValueStoreAPIService ActRunsLastKeyValueStorePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultKeyValueStoreAPI.ActRunsLastKeyValueStorePut(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultKeyValueStoreAPIService ActRunsLastKeyValueStoreRecordDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var recordKey string

		httpRes, err := apiClient.LastActorRunsDefaultKeyValueStoreAPI.ActRunsLastKeyValueStoreRecordDelete(context.Background(), actorId, recordKey).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultKeyValueStoreAPIService ActRunsLastKeyValueStoreRecordGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var recordKey string

		resp, httpRes, err := apiClient.LastActorRunsDefaultKeyValueStoreAPI.ActRunsLastKeyValueStoreRecordGet(context.Background(), actorId, recordKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultKeyValueStoreAPIService ActRunsLastKeyValueStoreRecordPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var recordKey string

		resp, httpRes, err := apiClient.LastActorRunsDefaultKeyValueStoreAPI.ActRunsLastKeyValueStoreRecordPost(context.Background(), actorId, recordKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultKeyValueStoreAPIService ActRunsLastKeyValueStoreRecordPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var recordKey string

		resp, httpRes, err := apiClient.LastActorRunsDefaultKeyValueStoreAPI.ActRunsLastKeyValueStoreRecordPut(context.Background(), actorId, recordKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultKeyValueStoreAPIService ActRunsLastKeyValueStoreRecordsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultKeyValueStoreAPI.ActRunsLastKeyValueStoreRecordsGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
