/*
Apify API

Testing StorageRequestQueuesRequestsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_StorageRequestQueuesRequestsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StorageRequestQueuesRequestsAPIService RequestQueueRequestDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string
		var requestId string

		httpRes, err := apiClient.StorageRequestQueuesRequestsAPI.RequestQueueRequestDelete(context.Background(), queueId, requestId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesRequestsAPIService RequestQueueRequestGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string
		var requestId string

		resp, httpRes, err := apiClient.StorageRequestQueuesRequestsAPI.RequestQueueRequestGet(context.Background(), queueId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesRequestsAPIService RequestQueueRequestPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string
		var requestId string

		resp, httpRes, err := apiClient.StorageRequestQueuesRequestsAPI.RequestQueueRequestPut(context.Background(), queueId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesRequestsAPIService RequestQueueRequestsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string

		resp, httpRes, err := apiClient.StorageRequestQueuesRequestsAPI.RequestQueueRequestsGet(context.Background(), queueId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesRequestsAPIService RequestQueueRequestsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string

		resp, httpRes, err := apiClient.StorageRequestQueuesRequestsAPI.RequestQueueRequestsPost(context.Background(), queueId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
