/*
Apify API

Testing ActorsActorVersionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_ActorsActorVersionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ActorsActorVersionsAPIService ActVersionDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var versionNumber string

		resp, httpRes, err := apiClient.ActorsActorVersionsAPI.ActVersionDelete(context.Background(), actorId, versionNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorVersionsAPIService ActVersionEnvVarDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var versionNumber string
		var envVarName string

		resp, httpRes, err := apiClient.ActorsActorVersionsAPI.ActVersionEnvVarDelete(context.Background(), actorId, versionNumber, envVarName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorVersionsAPIService ActVersionEnvVarGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var versionNumber string
		var envVarName string

		resp, httpRes, err := apiClient.ActorsActorVersionsAPI.ActVersionEnvVarGet(context.Background(), actorId, versionNumber, envVarName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorVersionsAPIService ActVersionEnvVarPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var versionNumber string
		var envVarName string

		resp, httpRes, err := apiClient.ActorsActorVersionsAPI.ActVersionEnvVarPost(context.Background(), actorId, versionNumber, envVarName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorVersionsAPIService ActVersionEnvVarPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var versionNumber string
		var envVarName string

		resp, httpRes, err := apiClient.ActorsActorVersionsAPI.ActVersionEnvVarPut(context.Background(), actorId, versionNumber, envVarName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorVersionsAPIService ActVersionEnvVarsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var versionNumber string

		resp, httpRes, err := apiClient.ActorsActorVersionsAPI.ActVersionEnvVarsGet(context.Background(), actorId, versionNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorVersionsAPIService ActVersionEnvVarsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var versionNumber string

		resp, httpRes, err := apiClient.ActorsActorVersionsAPI.ActVersionEnvVarsPost(context.Background(), actorId, versionNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorVersionsAPIService ActVersionGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var versionNumber string

		resp, httpRes, err := apiClient.ActorsActorVersionsAPI.ActVersionGet(context.Background(), actorId, versionNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorVersionsAPIService ActVersionPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var versionNumber string

		resp, httpRes, err := apiClient.ActorsActorVersionsAPI.ActVersionPost(context.Background(), actorId, versionNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorVersionsAPIService ActVersionPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var versionNumber string

		resp, httpRes, err := apiClient.ActorsActorVersionsAPI.ActVersionPut(context.Background(), actorId, versionNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorVersionsAPIService ActVersionsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.ActorsActorVersionsAPI.ActVersionsGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorVersionsAPIService ActVersionsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.ActorsActorVersionsAPI.ActVersionsPost(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
