/*
Apify API

Testing ActorsActorRunsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_ActorsActorRunsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ActorsActorRunsAPIService ActRunAbortPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var runId string

		resp, httpRes, err := apiClient.ActorsActorRunsAPI.ActRunAbortPost(context.Background(), actorId, runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorRunsAPIService ActRunGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var runId string

		resp, httpRes, err := apiClient.ActorsActorRunsAPI.ActRunGet(context.Background(), actorId, runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorRunsAPIService ActRunMetamorphPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var runId string

		resp, httpRes, err := apiClient.ActorsActorRunsAPI.ActRunMetamorphPost(context.Background(), actorId, runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorRunsAPIService ActRunResurrectPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var runId string

		resp, httpRes, err := apiClient.ActorsActorRunsAPI.ActRunResurrectPost(context.Background(), actorId, runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorRunsAPIService ActRunSyncGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.ActorsActorRunsAPI.ActRunSyncGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorRunsAPIService ActRunSyncGetDatasetItemsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.ActorsActorRunsAPI.ActRunSyncGetDatasetItemsGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorRunsAPIService ActRunSyncGetDatasetItemsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.ActorsActorRunsAPI.ActRunSyncGetDatasetItemsPost(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorRunsAPIService ActRunSyncPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.ActorsActorRunsAPI.ActRunSyncPost(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorRunsAPIService ActRunsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.ActorsActorRunsAPI.ActRunsGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorRunsAPIService ActRunsLastGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.ActorsActorRunsAPI.ActRunsLastGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorRunsAPIService ActRunsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.ActorsActorRunsAPI.ActRunsPost(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
