/*
Apify API

Testing LastActorTaskRunsRebootAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_LastActorTaskRunsRebootAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LastActorTaskRunsRebootAPIService ActorTaskRunsLastRebootPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsRebootAPI.ActorTaskRunsLastRebootPost(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
