/*
Apify API

Testing ActorTasksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_ActorTasksAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ActorTasksAPIService ActorTaskDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTaskDelete(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTaskGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTaskGet(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTaskInputGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTaskInputGet(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTaskInputPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTaskInputPut(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTaskPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTaskPut(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTaskRunSyncGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTaskRunSyncGet(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTaskRunSyncGetDatasetItemsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTaskRunSyncGetDatasetItemsGet(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTaskRunSyncGetDatasetItemsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTaskRunSyncGetDatasetItemsPost(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTaskRunSyncPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTaskRunSyncPost(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTaskRunsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTaskRunsGet(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTaskRunsLastGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTaskRunsLastGet(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTaskRunsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTaskRunsPost(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTaskWebhooksGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTaskWebhooksGet(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTasksGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTasksGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorTasksAPIService ActorTasksPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ActorTasksAPI.ActorTasksPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
