/*
Apify API

Testing LastActorTaskRunsDefaultKeyValueStoreAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_LastActorTaskRunsDefaultKeyValueStoreAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LastActorTaskRunsDefaultKeyValueStoreAPIService ActorTaskRunsLastKeyValueStoreDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		httpRes, err := apiClient.LastActorTaskRunsDefaultKeyValueStoreAPI.ActorTaskRunsLastKeyValueStoreDelete(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultKeyValueStoreAPIService ActorTaskRunsLastKeyValueStoreGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultKeyValueStoreAPI.ActorTaskRunsLastKeyValueStoreGet(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultKeyValueStoreAPIService ActorTaskRunsLastKeyValueStoreKeysGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultKeyValueStoreAPI.ActorTaskRunsLastKeyValueStoreKeysGet(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultKeyValueStoreAPIService ActorTaskRunsLastKeyValueStorePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultKeyValueStoreAPI.ActorTaskRunsLastKeyValueStorePut(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultKeyValueStoreAPIService ActorTaskRunsLastKeyValueStoreRecordDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string
		var recordKey string

		httpRes, err := apiClient.LastActorTaskRunsDefaultKeyValueStoreAPI.ActorTaskRunsLastKeyValueStoreRecordDelete(context.Background(), actorTaskId, recordKey).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultKeyValueStoreAPIService ActorTaskRunsLastKeyValueStoreRecordGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string
		var recordKey string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultKeyValueStoreAPI.ActorTaskRunsLastKeyValueStoreRecordGet(context.Background(), actorTaskId, recordKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultKeyValueStoreAPIService ActorTaskRunsLastKeyValueStoreRecordPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string
		var recordKey string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultKeyValueStoreAPI.ActorTaskRunsLastKeyValueStoreRecordPost(context.Background(), actorTaskId, recordKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultKeyValueStoreAPIService ActorTaskRunsLastKeyValueStoreRecordPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string
		var recordKey string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultKeyValueStoreAPI.ActorTaskRunsLastKeyValueStoreRecordPut(context.Background(), actorTaskId, recordKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorTaskRunsDefaultKeyValueStoreAPIService ActorTaskRunsLastKeyValueStoreRecordsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorTaskId string

		resp, httpRes, err := apiClient.LastActorTaskRunsDefaultKeyValueStoreAPI.ActorTaskRunsLastKeyValueStoreRecordsGet(context.Background(), actorTaskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
