/*
Apify API

Testing LastActorRunsDefaultRequestQueueAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_LastActorRunsDefaultRequestQueueAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueDelete(context.Background(), actorId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueHeadGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueHeadGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueHeadLockPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueHeadLockPost(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueuePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueuePut(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueRequestDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var requestId string

		httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueRequestDelete(context.Background(), actorId, requestId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueRequestGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var requestId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueRequestGet(context.Background(), actorId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueRequestLockDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var requestId string

		httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueRequestLockDelete(context.Background(), actorId, requestId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueRequestLockPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var requestId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueRequestLockPut(context.Background(), actorId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueRequestPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var requestId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueRequestPut(context.Background(), actorId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueRequestsBatchDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueRequestsBatchDelete(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueRequestsBatchPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueRequestsBatchPost(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueRequestsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueRequestsGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueRequestsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueRequestsPost(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LastActorRunsDefaultRequestQueueAPIService ActRunsLastRequestQueueRequestsUnlockPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsDefaultRequestQueueAPI.ActRunsLastRequestQueueRequestsUnlockPost(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
