/*
Apify API

Testing ActorsActorBuildsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_ActorsActorBuildsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ActorsActorBuildsAPIService ActBuildAbortPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var buildId string

		resp, httpRes, err := apiClient.ActorsActorBuildsAPI.ActBuildAbortPost(context.Background(), actorId, buildId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorBuildsAPIService ActBuildDefaultGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.ActorsActorBuildsAPI.ActBuildDefaultGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorBuildsAPIService ActBuildGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var buildId string

		resp, httpRes, err := apiClient.ActorsActorBuildsAPI.ActBuildGet(context.Background(), actorId, buildId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorBuildsAPIService ActBuildsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.ActorsActorBuildsAPI.ActBuildsGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorBuildsAPIService ActBuildsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.ActorsActorBuildsAPI.ActBuildsPost(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorsActorBuildsAPIService ActOpenapiJsonGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string
		var buildId string

		resp, httpRes, err := apiClient.ActorsActorBuildsAPI.ActOpenapiJsonGet(context.Background(), actorId, buildId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
