/*
Apify API

Testing ActorRunsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_ActorRunsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ActorRunsAPIService ActorRunAbortPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.ActorRunsAPI.ActorRunAbortPost(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorRunsAPIService ActorRunDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		httpRes, err := apiClient.ActorRunsAPI.ActorRunDelete(context.Background(), runId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorRunsAPIService ActorRunGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.ActorRunsAPI.ActorRunGet(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorRunsAPIService ActorRunLogGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.ActorRunsAPI.ActorRunLogGet(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorRunsAPIService ActorRunMetamorphPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.ActorRunsAPI.ActorRunMetamorphPost(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorRunsAPIService ActorRunPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.ActorRunsAPI.ActorRunPut(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorRunsAPIService ActorRunRebootPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.ActorRunsAPI.ActorRunRebootPost(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorRunsAPIService ActorRunsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ActorRunsAPI.ActorRunsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorRunsAPIService PostChargeRun", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.ActorRunsAPI.PostChargeRun(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActorRunsAPIService PostResurrectRun", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.ActorRunsAPI.PostResurrectRun(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
