/*
Apify API

Testing WebhooksWebhookDispatchesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_WebhooksWebhookDispatchesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WebhooksWebhookDispatchesAPIService WebhookDispatchGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dispatchId string

		resp, httpRes, err := apiClient.WebhooksWebhookDispatchesAPI.WebhookDispatchGet(context.Background(), dispatchId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksWebhookDispatchesAPIService WebhookDispatchesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WebhooksWebhookDispatchesAPI.WebhookDispatchesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
