/*
Apify API

Testing LastActorRunsLogAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_LastActorRunsLogAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LastActorRunsLogAPIService ActRunsLastLogGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var actorId string

		resp, httpRes, err := apiClient.LastActorRunsLogAPI.ActRunsLastLogGet(context.Background(), actorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
