/*
Apify API

Testing StorageRequestQueuesRequestsLocksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_StorageRequestQueuesRequestsLocksAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StorageRequestQueuesRequestsLocksAPIService RequestQueueHeadGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string

		resp, httpRes, err := apiClient.StorageRequestQueuesRequestsLocksAPI.RequestQueueHeadGet(context.Background(), queueId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesRequestsLocksAPIService RequestQueueHeadLockPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string

		resp, httpRes, err := apiClient.StorageRequestQueuesRequestsLocksAPI.RequestQueueHeadLockPost(context.Background(), queueId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesRequestsLocksAPIService RequestQueueRequestLockDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string
		var requestId string

		httpRes, err := apiClient.StorageRequestQueuesRequestsLocksAPI.RequestQueueRequestLockDelete(context.Background(), queueId, requestId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesRequestsLocksAPIService RequestQueueRequestLockPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string
		var requestId string

		resp, httpRes, err := apiClient.StorageRequestQueuesRequestsLocksAPI.RequestQueueRequestLockPut(context.Background(), queueId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageRequestQueuesRequestsLocksAPIService RequestQueueRequestsUnlockPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queueId string

		resp, httpRes, err := apiClient.StorageRequestQueuesRequestsLocksAPI.RequestQueueRequestsUnlockPost(context.Background(), queueId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
