/*
Apify API

Testing DefaultRequestQueueAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/apify/apify-client-go"
)

func Test_apifyclient_DefaultRequestQueueAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueDelete(context.Background(), runId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueGet(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueHeadGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueHeadGet(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueHeadLockPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueHeadLockPost(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueuePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueuePut(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueRequestDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string
		var requestId string

		httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueRequestDelete(context.Background(), runId, requestId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueRequestGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string
		var requestId string

		resp, httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueRequestGet(context.Background(), runId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueRequestLockDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string
		var requestId string

		httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueRequestLockDelete(context.Background(), runId, requestId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueRequestLockPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string
		var requestId string

		resp, httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueRequestLockPut(context.Background(), runId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueRequestPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string
		var requestId string

		resp, httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueRequestPut(context.Background(), runId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueRequestsBatchDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueRequestsBatchDelete(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueRequestsBatchPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueRequestsBatchPost(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueRequestsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueRequestsGet(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueRequestsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueRequestsPost(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultRequestQueueAPIService ActorRunRequestQueueRequestsUnlockPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var runId string

		resp, httpRes, err := apiClient.DefaultRequestQueueAPI.ActorRunRequestQueueRequestsUnlockPost(context.Background(), runId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
